# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bcs_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys

class Ui_MainWindow(object):
    def setupUi(self, MainWindow, tanks_amount_value, apc_amount_value, ifv_amount_value, total_as_vehicles, vehicles_decision,
                ev_amount_value, aa_amount_value, total_sp_vehicles, sp_decision,
                tart_amount_value, spart_amount_value, total_artillery, art_decision,
                aap_amount_value, ta_amount_value, th_amount_value, ah_amount_value, total_aviation, av_decision,
                troops_amount_value, troops_decision
                ):


        self.tanks_amount_value = tanks_amount_value
        self.apc_amount_value = apc_amount_value
        self.ifv_amount_value = ifv_amount_value
        self.total_as_vehicles = total_as_vehicles
        self.vehicles_decision = vehicles_decision

        self.ev_amount_value = ev_amount_value
        self.aa_amount_value = aa_amount_value
        self.total_sp_vehicles = total_sp_vehicles
        self.sp_decision = sp_decision

        self.tart_amount_value = tart_amount_value
        self.spart_amount_value = spart_amount_value
        self.total_artillery = total_artillery
        self.art_decision = art_decision

        self.aap_amount_value = aap_amount_value
        self.ta_amount_value = ta_amount_value
        self.th_amount_value = th_amount_value
        self.ah_amount_value = ah_amount_value
        self.total_aviation = total_aviation
        self.av_decision = av_decision


        self.troops_amount_value = troops_amount_value
        self.troops_decision = troops_decision






        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(709, 778)
        MainWindow.setStyleSheet("background-color: rgb(49, 48, 51);\n"
"background-color: rgb(148, 148, 148);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.as_vehicles = QtWidgets.QGroupBox(self.centralwidget)
        self.as_vehicles.setGeometry(QtCore.QRect(360, 0, 341, 241))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.as_vehicles.setFont(font)
        self.as_vehicles.setStyleSheet("background-color: rgb(120, 120, 120);")
        self.as_vehicles.setObjectName("as_vehicles")
        self.tanks = QtWidgets.QLabel(self.as_vehicles)
        self.tanks.setGeometry(QtCore.QRect(20, 40, 60, 16))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.tanks.setFont(font)
        self.tanks.setObjectName("tanks")
        self.apc = QtWidgets.QLabel(self.as_vehicles)
        self.apc.setGeometry(QtCore.QRect(20, 80, 60, 16))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.apc.setFont(font)
        self.apc.setObjectName("apc")
        self.ifv = QtWidgets.QLabel(self.as_vehicles)
        self.ifv.setGeometry(QtCore.QRect(20, 120, 60, 16))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ifv.setFont(font)
        self.ifv.setObjectName("ifv")
        self.t_vehicles = QtWidgets.QLabel(self.as_vehicles)
        self.t_vehicles.setGeometry(QtCore.QRect(20, 160, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.t_vehicles.setFont(font)
        self.t_vehicles.setObjectName("t_vehicles")
        self.tanks_amount = QtWidgets.QLabel(self.as_vehicles)
        self.tanks_amount.setGeometry(QtCore.QRect(80, 40, 60, 16))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.tanks_amount.setFont(font)
        self.tanks_amount.setObjectName("tanks_amount")
        self.apc_amount = QtWidgets.QLabel(self.as_vehicles)
        self.apc_amount.setGeometry(QtCore.QRect(70, 80, 60, 16))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.apc_amount.setFont(font)
        self.apc_amount.setObjectName("apc_amount")
        self.ifv_amount = QtWidgets.QLabel(self.as_vehicles)
        self.ifv_amount.setGeometry(QtCore.QRect(60, 120, 60, 16))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ifv_amount.setFont(font)
        self.ifv_amount.setObjectName("ifv_amount")
        self.t_vehicles_amount = QtWidgets.QLabel(self.as_vehicles)
        self.t_vehicles_amount.setGeometry(QtCore.QRect(145, 160, 60, 16))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.t_vehicles_amount.setFont(font)
        self.t_vehicles_amount.setObjectName("t_vehicles_amount")
        self.v_dec = QtWidgets.QLabel(self.as_vehicles)
        self.v_dec.setGeometry(QtCore.QRect(20, 200, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.v_dec.setFont(font)
        self.v_dec.setObjectName("v_dec")
        self.v_dec_obj = QtWidgets.QLabel(self.as_vehicles)
        self.v_dec_obj.setGeometry(QtCore.QRect(100, 200, 60, 16))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.v_dec_obj.setFont(font)
        self.v_dec_obj.setObjectName("v_dec_obj")
        self.s_vehicles = QtWidgets.QGroupBox(self.centralwidget)
        self.s_vehicles.setGeometry(QtCore.QRect(360, 250, 341, 191))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.s_vehicles.setFont(font)
        self.s_vehicles.setStyleSheet("background-color: rgb(120, 120, 120);")
        self.s_vehicles.setObjectName("s_vehicles")
        self.ev = QtWidgets.QLabel(self.s_vehicles)
        self.ev.setGeometry(QtCore.QRect(20, 40, 60, 16))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ev.setFont(font)
        self.ev.setObjectName("ev")
        self.aa = QtWidgets.QLabel(self.s_vehicles)
        self.aa.setGeometry(QtCore.QRect(20, 80, 60, 16))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.aa.setFont(font)
        self.aa.setObjectName("aa")
        self.t_spec = QtWidgets.QLabel(self.s_vehicles)
        self.t_spec.setGeometry(QtCore.QRect(20, 120, 181, 16))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.t_spec.setFont(font)
        self.t_spec.setObjectName("t_spec")
        self.ev_amount = QtWidgets.QLabel(self.s_vehicles)
        self.ev_amount.setGeometry(QtCore.QRect(60, 40, 60, 16))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ev_amount.setFont(font)
        self.ev_amount.setObjectName("ev_amount")
        self.aa_amount = QtWidgets.QLabel(self.s_vehicles)
        self.aa_amount.setGeometry(QtCore.QRect(60, 80, 60, 16))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.aa_amount.setFont(font)
        self.aa_amount.setObjectName("aa_amount")
        self.t_spec_amount = QtWidgets.QLabel(self.s_vehicles)
        self.t_spec_amount.setGeometry(QtCore.QRect(205, 120, 60, 16))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.t_spec_amount.setFont(font)
        self.t_spec_amount.setObjectName("t_spec_amount")
        self.s_dec = QtWidgets.QLabel(self.s_vehicles)
        self.s_dec.setGeometry(QtCore.QRect(20, 160, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.s_dec.setFont(font)
        self.s_dec.setObjectName("s_dec")
        self.s_dec_obj = QtWidgets.QLabel(self.s_vehicles)
        self.s_dec_obj.setGeometry(QtCore.QRect(105, 160, 60, 16))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.s_dec_obj.setFont(font)
        self.s_dec_obj.setObjectName("s_dec_obj")
        self.troops = QtWidgets.QGroupBox(self.centralwidget)
        self.troops.setGeometry(QtCore.QRect(360, 450, 341, 111))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.troops.setFont(font)
        self.troops.setStyleSheet("background-color: rgb(120, 120, 120);")
        self.troops.setObjectName("troops")
        self.t_troops = QtWidgets.QLabel(self.troops)
        self.t_troops.setGeometry(QtCore.QRect(20, 40, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.t_troops.setFont(font)
        self.t_troops.setObjectName("t_troops")
        self.troops_amount = QtWidgets.QLabel(self.troops)
        self.troops_amount.setGeometry(QtCore.QRect(130, 40, 60, 16))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.troops_amount.setFont(font)
        self.troops_amount.setObjectName("troops_amount")
        self.t_dec = QtWidgets.QLabel(self.troops)
        self.t_dec.setGeometry(QtCore.QRect(20, 80, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.t_dec.setFont(font)
        self.t_dec.setObjectName("t_dec")
        self.t_dec_obj = QtWidgets.QLabel(self.troops)
        self.t_dec_obj.setGeometry(QtCore.QRect(100, 80, 60, 16))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.t_dec_obj.setFont(font)
        self.t_dec_obj.setObjectName("t_dec_obj")
        self.artillery = QtWidgets.QGroupBox(self.centralwidget)
        self.artillery.setGeometry(QtCore.QRect(360, 570, 341, 191))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.artillery.setFont(font)
        self.artillery.setStyleSheet("background-color: rgb(120, 120, 120);")
        self.artillery.setObjectName("artillery")
        self.tart = QtWidgets.QLabel(self.artillery)
        self.tart.setGeometry(QtCore.QRect(20, 40, 60, 16))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.tart.setFont(font)
        self.tart.setObjectName("tart")
        self.spart = QtWidgets.QLabel(self.artillery)
        self.spart.setGeometry(QtCore.QRect(20, 80, 60, 16))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.spart.setFont(font)
        self.spart.setObjectName("spart")
        self.tot_art = QtWidgets.QLabel(self.artillery)
        self.tot_art.setGeometry(QtCore.QRect(20, 120, 181, 16))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.tot_art.setFont(font)
        self.tot_art.setObjectName("tot_art")
        self.tart_amount = QtWidgets.QLabel(self.artillery)
        self.tart_amount.setGeometry(QtCore.QRect(80, 40, 60, 16))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.tart_amount.setFont(font)
        self.tart_amount.setObjectName("tart_amount")
        self.spart_amount = QtWidgets.QLabel(self.artillery)
        self.spart_amount.setGeometry(QtCore.QRect(90, 80, 60, 16))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.spart_amount.setFont(font)
        self.spart_amount.setObjectName("spart_amount")
        self.tot_art_amount = QtWidgets.QLabel(self.artillery)
        self.tot_art_amount.setGeometry(QtCore.QRect(140, 120, 60, 16))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.tot_art_amount.setFont(font)
        self.tot_art_amount.setObjectName("tot_art_amount")
        self.art_dec = QtWidgets.QLabel(self.artillery)
        self.art_dec.setGeometry(QtCore.QRect(20, 160, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.art_dec.setFont(font)
        self.art_dec.setObjectName("art_dec")
        self.art_dec_obj = QtWidgets.QLabel(self.artillery)
        self.art_dec_obj.setGeometry(QtCore.QRect(105, 160, 60, 16))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.art_dec_obj.setFont(font)
        self.art_dec_obj.setObjectName("art_dec_obj")
        self.aviation = QtWidgets.QGroupBox(self.centralwidget)
        self.aviation.setGeometry(QtCore.QRect(10, 0, 341, 291))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.aviation.setFont(font)
        self.aviation.setStyleSheet("background-color: rgb(120, 120, 120);\n"
"border-color: rgb(0, 0, 0);")
        self.aviation.setObjectName("aviation")
        self.aap = QtWidgets.QLabel(self.aviation)
        self.aap.setGeometry(QtCore.QRect(20, 40, 60, 16))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.aap.setFont(font)
        self.aap.setObjectName("aap")
        self.ah = QtWidgets.QLabel(self.aviation)
        self.ah.setGeometry(QtCore.QRect(20, 80, 60, 16))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ah.setFont(font)
        self.ah.setObjectName("ah")
        self.th = QtWidgets.QLabel(self.aviation)
        self.th.setGeometry(QtCore.QRect(20, 120, 60, 16))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.th.setFont(font)
        self.th.setObjectName("th")
        self.ta = QtWidgets.QLabel(self.aviation)
        self.ta.setGeometry(QtCore.QRect(20, 160, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ta.setFont(font)
        self.ta.setObjectName("ta")
        self.aap_amount = QtWidgets.QLabel(self.aviation)
        self.aap_amount.setGeometry(QtCore.QRect(70, 40, 60, 16))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.aap_amount.setFont(font)
        self.aap_amount.setObjectName("aap_amount")
        self.ah_amount = QtWidgets.QLabel(self.aviation)
        self.ah_amount.setGeometry(QtCore.QRect(60, 80, 60, 16))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ah_amount.setFont(font)
        self.ah_amount.setObjectName("ah_amount")
        self.th_amount = QtWidgets.QLabel(self.aviation)
        self.th_amount.setGeometry(QtCore.QRect(60, 120, 60, 16))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.th_amount.setFont(font)
        self.th_amount.setObjectName("th_amount")
        self.ta_amount = QtWidgets.QLabel(self.aviation)
        self.ta_amount.setGeometry(QtCore.QRect(60, 160, 60, 16))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ta_amount.setFont(font)
        self.ta_amount.setObjectName("ta_amount")
        self.av_dec = QtWidgets.QLabel(self.aviation)
        self.av_dec.setGeometry(QtCore.QRect(20, 240, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.av_dec.setFont(font)
        self.av_dec.setObjectName("av_dec")
        self.av_dec_obj = QtWidgets.QLabel(self.aviation)
        self.av_dec_obj.setGeometry(QtCore.QRect(100, 240, 60, 16))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.av_dec_obj.setFont(font)
        self.av_dec_obj.setObjectName("av_dec_obj")
        self.tot_av = QtWidgets.QLabel(self.aviation)
        self.tot_av.setGeometry(QtCore.QRect(20, 200, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.tot_av.setFont(font)
        self.tot_av.setObjectName("tot_av")
        self.tot_av_amount = QtWidgets.QLabel(self.aviation)
        self.tot_av_amount.setGeometry(QtCore.QRect(140, 200, 60, 16))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.tot_av_amount.setFont(font)
        self.tot_av_amount.setObjectName("tot_av_amount")
        self.stop_btn = QtWidgets.QPushButton(self.centralwidget)
        self.stop_btn.setGeometry(QtCore.QRect(10, 700, 191, 71))
        self.stop_btn.setStyleSheet("background-color: rgb(86, 86, 86);")
        self.stop_btn.setObjectName("stop_btn")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.as_vehicles.setTitle(_translate("MainWindow", "Assault vehicles"))
        self.tanks.setText(_translate("MainWindow", "Tanks:"))
        self.apc.setText(_translate("MainWindow", "APC:"))
        self.ifv.setText(_translate("MainWindow", "IFV:"))
        self.t_vehicles.setText(_translate("MainWindow", "Total vehicles:"))
        self.tanks_amount.setText(_translate("MainWindow", str(self.tanks_amount_value)))
        self.apc_amount.setText(_translate("MainWindow", str(self.apc_amount_value)))
        self.ifv_amount.setText(_translate("MainWindow", str(self.ifv_amount_value)))
        self.t_vehicles_amount.setText(_translate("MainWindow", str(self.total_as_vehicles)))
        self.v_dec.setText(_translate("MainWindow", "Decision:"))
        self.v_dec_obj.setText(_translate("MainWindow", str(self.vehicles_decision)))


        self.s_vehicles.setTitle(_translate("MainWindow", "Special vehicles"))
        self.ev.setText(_translate("MainWindow", "EV:"))
        self.aa.setText(_translate("MainWindow", "AA:"))
        self.t_spec.setText(_translate("MainWindow", "Total special vehicles:"))


        self.ev_amount.setText(_translate("MainWindow", str(self.ev_amount_value)))
        self.aa_amount.setText(_translate("MainWindow", str(self.aa_amount_value)))
        self.t_spec_amount.setText(_translate("MainWindow", str(self.total_sp_vehicles)))
        self.s_dec.setText(_translate("MainWindow", "Decision:"))
        self.s_dec_obj.setText(_translate("MainWindow", str(self.sp_decision)))



        self.troops.setTitle(_translate("MainWindow", "Troops"))
        self.t_troops.setText(_translate("MainWindow", "Total troops:"))
        self.troops_amount.setText(_translate("MainWindow", str(self.troops_amount_value)))
        self.t_dec.setText(_translate("MainWindow", "Decision:"))
        self.t_dec_obj.setText(_translate("MainWindow", str(self.troops_decision)))


        self.artillery.setTitle(_translate("MainWindow", "Artillery"))
        self.tart.setText(_translate("MainWindow", "TART:"))
        self.spart.setText(_translate("MainWindow", "SPART:"))
        self.tot_art.setText(_translate("MainWindow", "Total artillery:"))
        self.tart_amount.setText(_translate("MainWindow", str(self.tart_amount_value)))
        self.spart_amount.setText(_translate("MainWindow", str(self.spart_amount_value)))
        self.tot_art_amount.setText(_translate("MainWindow", str(self.total_artillery)))
        self.art_dec.setText(_translate("MainWindow", "Decision:"))
        self.art_dec_obj.setText(_translate("MainWindow", str(self.art_decision)))

        self.aviation.setTitle(_translate("MainWindow", "Aviation"))
        self.aap.setText(_translate("MainWindow", "AAP:"))
        self.ah.setText(_translate("MainWindow", "AH:"))
        self.th.setText(_translate("MainWindow", "TH:"))
        self.ta.setText(_translate("MainWindow", "TA:"))
        self.aap_amount.setText(_translate("MainWindow", str(self.aap_amount_value)))
        self.ah_amount.setText(_translate("MainWindow", str(self.ah_amount_value)))
        self.th_amount.setText(_translate("MainWindow", str(self.th_amount_value)))
        self.ta_amount.setText(_translate("MainWindow", str(self.ta_amount_value)))
        self.av_dec.setText(_translate("MainWindow", "Decision:"))
        self.av_dec_obj.setText(_translate("MainWindow", str(self.av_decision)))
        self.tot_av.setText(_translate("MainWindow", "Total aviation:"))
        self.tot_av_amount.setText(_translate("MainWindow", str(self.total_aviation)))

        self.stop_btn.setText(_translate("MainWindow", "Stop translation"))



def interface(tank_ammount, apc_ammount, ifv_ammount, total_vehicles_ammount, vehicles_descision,
               ev_ammount, aa_ammount, total_specials_ammount, vehicle_descision,
               tart_ammount, spart_ammount, total_artillery_units, artillery_descision,
               aap_ammount, ta_ammount, th_ammount, ah_ammount, total_flying_units, flying_descision,
               total_troops, troops_descision):

    from main import main

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow,
               tank_ammount, apc_ammount, ifv_ammount, total_vehicles_ammount, vehicle_descision,
               ev_ammount, aa_ammount, total_specials_ammount, vehicles_descision,
               tart_ammount, spart_ammount, total_artillery_units, artillery_descision,
               aap_ammount, ta_ammount, th_ammount, ah_ammount, total_flying_units, flying_descision,
               total_troops, troops_descision)
    MainWindow.show()

    sys.exit(app.exec_())




